Repository solana-labs/solana-program-library, pull requests merged in 2021-12, with the labels that each got.

#2609 (Docs) Update Coverage instructions with MacOS commands
  README.md
Labels: community

#2610 docs: Prefer non gendered pronouns
  docs/src/associated-token-account.md
  farms/README.md
Labels: automerge

#2616 docs: token: Added timelock program
  docs/src/token.md
Labels: community

#2624 Migrate to @solana/buffer-layout
  token/js/client/layout.js
  token/js/client/token.js
  token/js/flow-typed/npm/@solana/buffer-layout_vx.x.x.js
  token/js/flow-typed/npm/buffer-layout_vx.x.x.js
  token/js/module.d.ts
  token/js/module.flow.js
  token/js/package-lock.json
  token/js/package.json
  token/js/rollup.config.js
Labels: community

#2629 token-swap: Migrate to `@solana/buffer-layout`
  token-swap/js/package-lock.json
  token-swap/js/package.json
  token-swap/js/src/buffer-layout.d.ts
  token-swap/js/src/index.ts
  token-swap/js/src/layout.ts
Labels: community

#2625 fix: Fix typos
  binary-option/README.md
Labels: automerge, community

#2648 fix account list in token_swap instructions docs
  token-swap/program/src/instruction.rs
Labels: community

#2651 Fix typo in account.rs
  farms/farm-sdk/src/program/account.rs
Labels: community

#2102 Add token/rust: spl-token-api
  Cargo.lock
  Cargo.toml
  token/rust/Cargo.toml
  token/rust/src/client.rs
  token/rust/src/lib.rs
  token/rust/src/token.rs
  token/rust/tests/program-test.rs
Labels: community

#2635 farms: Add trade governance
  .gitignore
  farms/README.md
  farms/farm-client/Cargo.toml
  farms/farm-client/src/cli/config.rs
  farms/farm-client/src/cli/main.rs
  farms/farm-client/src/cli/printer.rs
  farms/farm-client/src/client.rs
  farms/farm-client/src/client/governance_instructions.rs
  farms/farm-client/src/client/pool_accounts_saber.rs
  farms/farm-client/src/client/pool_instructions.rs
  farms/farm-client/src/client/refdb_instructions.rs
  farms/farm-client/src/client/vault_instructions.rs
  farms/farm-ctrl/Cargo.toml
  farms/farm-ctrl/src/config.rs
  farms/farm-ctrl/src/get.rs
  farms/farm-ctrl/src/governance.rs
  farms/farm-ctrl/src/loaders/program.rs
  farms/farm-ctrl/src/main.rs
  farms/farm-ctrl/src/remove.rs
  farms/farm-ctrl/src/vault.rs
  farms/farm-sdk/src/id.rs
  farms/farm-sdk/src/instruction/vault.rs
  farms/farm-sdk/src/program/account.rs
  farms/farm-sdk/src/program/pda.rs
  farms/farm-sdk/src/program/protocol/raydium.rs
  farms/farm-sdk/src/refdb.rs
  farms/farm-sdk/src/token.rs
  farms/vaults/src/entrypoint.rs
  farms/vaults/src/strategies/rdm_stake_lp_compound/mod.rs
  farms/vaults/src/strategies/rdm_stake_lp_compound/withdraw_fees.rs
  farms/vaults/src/strategies/sbr_stake_lp_compound/mod.rs
  farms/vaults/src/strategies/sbr_stake_lp_compound/withdraw_fees.rs
  farms/vaults/src/traits.rs
  farms/vaults/src/user_info.rs
Labels: community

#2604 [stake-pool] js: web3 stake pool bindings
  stake-pool/js/.gitignore
  stake-pool/js/.prettierrc
  stake-pool/js/.prettierrc.yaml
  stake-pool/js/README.md
  stake-pool/js/babel.config.js
  stake-pool/js/package-lock.json
  stake-pool/js/package.json
  stake-pool/js/src/constants.ts
  stake-pool/js/src/copied-from-solana-web3/README.md
  stake-pool/js/src/copied-from-solana-web3/instruction.ts
  stake-pool/js/src/copied-from-solana-web3/layout.ts
  stake-pool/js/src/index.ts
  stake-pool/js/src/instructions.ts
  stake-pool/js/src/integration_test.ts
  stake-pool/js/src/layouts.ts
  stake-pool/js/src/schema.ts
  stake-pool/js/src/test.ts
  stake-pool/js/src/utils/index.ts
  stake-pool/js/src/utils/math.ts
  stake-pool/js/src/utils/program-address.ts
  stake-pool/js/src/utils/stake.ts
  stake-pool/js/src/utils/token.ts
  stake-pool/js/test/equal.ts
  stake-pool/js/test/instructions.test.ts
  stake-pool/js/test/integration.test.ts
  stake-pool/js/test/layouts.test.ts
  stake-pool/js/test/mocks.ts
  stake-pool/js/tsconfig.json
Labels: community

#2669 fix: wrong argument to transfer
  docs/src/token.md
Labels: community

#2667 fix grcov dependency checking
  coverage.sh
Labels: community

#2678 add test for memo
  memo/program/src/lib.rs
Labels: community

#2673 [token-swap] Upgrade PyO3 from 0.12.3 to 0.15.1
  token-swap/program/sim/Cargo.toml
  token-swap/program/sim/src/lib.rs
Labels: community
