Repository solana-labs/solana-program-library, pull requests merged in 2021-11, with the labels that each got.

#2554 Allow GC to close empty associated accounts
  token/cli/src/main.rs
Labels: community

#2569 Fix typo in main.rs
  token/cli/src/main.rs
Labels: automerge, community

#2558 Implement multiple output format for spl-stake-pool list-all
  Cargo.lock
  stake-pool/cli/Cargo.toml
  stake-pool/cli/src/client.rs
  stake-pool/cli/src/main.rs
  stake-pool/cli/src/output.rs
Labels: community

#2570 name service: allow parent name owner to update records
  name-service/js/src/bindings.ts
  name-service/js/src/instructions.ts
  name-service/js/src/twitter.ts
  name-service/program/src/instruction.rs
  name-service/program/src/processor.rs
  name-service/program/tests/functional.rs
Labels: community

#2593 spl-token: provide more useful output when using create-token with the output option and small redesign of token cli architecture
  token/cli/src/bench.rs
  token/cli/src/main.rs
  token/cli/src/output.rs
Labels: automerge, community

#2601 Update comment on state.rs regarding is_native
  token/program/src/state.rs
Labels: community

#2603 Adds "solana-version" to "patch.crates-io.sh"
  patch.crates-io.sh
Labels: automerge
