Repository solana-labs/solana-program-library, pull requests merged in 2021-08, with the labels that each got.

#2056 Binary Option
  Cargo.lock
  Cargo.toml
  binary-option/README.md
  binary-option/client/__init__.py
  binary-option/client/binary_option.py
  binary-option/client/requirements.txt
  binary-option/client/test.py
  binary-option/program/Cargo.toml
  binary-option/program/program_id.md
  binary-option/program/src/entrypoint.rs
  binary-option/program/src/error.rs
  binary-option/program/src/instruction.rs
  binary-option/program/src/lib.rs
  binary-option/program/src/processor.rs
  binary-option/program/src/spl_utils.rs
  binary-option/program/src/state.rs
  binary-option/program/src/system_utils.rs
  binary-option/program/src/validation_utils.rs
Labels: community

#2145 token: fix ts for @solana/spl-token
  token/js/module.d.ts
  token/js/module.flow.js
Labels: community

#2141 Stake pool/liquid deposits (rebased on new master)
  stake-pool/cli/scripts/deposit-withdraw.sh
  stake-pool/cli/src/main.rs
  stake-pool/program/src/error.rs
  stake-pool/program/src/instruction.rs
  stake-pool/program/src/lib.rs
  stake-pool/program/src/processor.rs
  stake-pool/program/src/state.rs
  stake-pool/program/tests/decrease.rs
  stake-pool/program/tests/deposit.rs
  stake-pool/program/tests/deposit_sol.rs
  stake-pool/program/tests/helpers/mod.rs
  stake-pool/program/tests/huge_pool.rs
  stake-pool/program/tests/increase.rs
  stake-pool/program/tests/initialize.rs
  stake-pool/program/tests/set_deposit_authority.rs
  stake-pool/program/tests/set_deposit_fee.rs
  stake-pool/program/tests/set_fee.rs
  stake-pool/program/tests/set_referral_fee.rs
  stake-pool/program/tests/set_withdrawal_fee.rs
  stake-pool/program/tests/update_stake_pool_balance.rs
  stake-pool/program/tests/update_validator_list_balance.rs
  stake-pool/program/tests/vsa_remove.rs
  stake-pool/program/tests/withdraw.rs
Labels: community

#2259 Add Anchor.toml for source verification
  Anchor.toml
Labels: community

#2279 Remove unused file
  feature-proposal/program/src/borsh_utils.rs
Labels: automerge

#2271 added support for curve params
  .gitignore
  token-swap/js/cli/main.ts
  token-swap/js/cli/token-swap-test.ts
  token-swap/js/src/index.ts
Labels: community

#2269 stake-pool: Update fee changes only once per epoch
  stake-pool/program/src/processor.rs
  stake-pool/program/tests/set_withdrawal_fee.rs
Labels: community

#2273 fix: stake-pool require signature in SetManager
  stake-pool/cli/src/main.rs
  stake-pool/program/src/instruction.rs
  stake-pool/program/src/processor.rs
  stake-pool/program/tests/set_manager.rs
Labels: community

#2278 stake-pool: Check that initialized accounts are distinct
  stake-pool/program/src/processor.rs
Labels: community

#2285 chore(token): expose transfer checked instruction
  token/js/module.d.ts
Labels: community

#2289 chore(token): add createTransferCheckedInstruction to flow-typed
  token/js/module.flow.js
Labels: automerge, community

#2272 fix stake-pool: preferred validator can be set to validator not part of the pool
  stake-pool/program/src/error.rs
  stake-pool/program/src/processor.rs
  stake-pool/program/tests/set_preferred.rs
Labels: community

#2270 stake-pool: `DepositStake` only issues tokens for `delegation.stake` + `min(undelegated_stake_rent, additional_lamports)`
  stake-pool/program/src/processor.rs
  stake-pool/program/tests/deposit.rs
  stake-pool/program/tests/helpers/mod.rs
  stake-pool/program/tests/initialize.rs
Labels: community

#2277 stake-pool: skip manager fee if invalid account, check new manager fee owned by `spl_token`
  stake-pool/program/src/processor.rs
  stake-pool/program/src/state.rs
  stake-pool/program/tests/helpers/mod.rs
  stake-pool/program/tests/withdraw.rs
Labels: community

#2286 Use stake pool's declared token ID rather than hard-coded
  stake-pool/program/src/instruction.rs
  stake-pool/program/tests/helpers/mod.rs
  stake-pool/program/tests/huge_pool.rs
Labels: community

#2287 token lending - bug fixes and flash loan receiver
  Cargo.lock
  Cargo.toml
  token-lending/flash_loan_receiver/Cargo.lock
  token-lending/flash_loan_receiver/Cargo.toml
  token-lending/flash_loan_receiver/Xargo.toml
  token-lending/flash_loan_receiver/src/entrypoint.rs
  token-lending/flash_loan_receiver/src/lib.rs
  token-lending/flash_loan_receiver/src/processor.rs
  token-lending/js/src/instructions/flashLoan.ts
  token-lending/js/src/instructions/initReserve.ts
  token-lending/js/src/util/layout.ts
  token-lending/program/src/instruction.rs
Labels: community

#2298 stake-pool: seed suffix to allow creating & discarding multiple transient stake accs
  stake-pool/program/src/lib.rs
  stake-pool/program/src/processor.rs
  stake-pool/program/src/state.rs
  stake-pool/program/tests/huge_pool.rs
  stake-pool/program/tests/vsa_add.rs
  stake-pool/program/tests/vsa_remove.rs
Labels: community
