Repository solana-labs/solana-program-library, pull requests merged in 2024-01, with the labels that each got.

#6014 feat: token-group interface js library
  .github/workflows/pull-request-js.yml
  .github/workflows/pull-request-token-group.yml
  ci/js-test-token-group.sh
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  token-group/js/.eslintignore
  token-group/js/.eslintrc
  token-group/js/.gitignore
  token-group/js/.mocharc.json
  token-group/js/.nojekyll
  token-group/js/.prettierignore
  token-group/js/.prettierrc
  token-group/js/LICENSE
  token-group/js/README.md
  token-group/js/package.json
  token-group/js/src/errors.ts
  token-group/js/src/index.ts
  token-group/js/src/instruction.ts
  token-group/js/src/state/index.ts
  token-group/js/src/state/tokenGroup.ts
  token-group/js/src/state/tokenGroupMember.ts
  token-group/js/test/instruction.test.ts
  token-group/js/test/state.test.ts
  token-group/js/tsconfig.all.json
  token-group/js/tsconfig.base.json
  token-group/js/tsconfig.cjs.json
  token-group/js/tsconfig.esm.json
  token-group/js/tsconfig.json
  token-group/js/tsconfig.root.json
  token-group/js/typedoc.json
Labels: community

#6017 docs: add token group docs
  docs/src/token-2022/extensions.mdx
  token-group/interface/README.md
Labels: do-not-close

#5997 transfer hook cli: add support for PDAs as extra metas
  Cargo.lock
  libraries/tlv-account-resolution/Cargo.toml
  libraries/tlv-account-resolution/src/seeds.rs
  token/transfer-hook/cli/Cargo.toml
  token/transfer-hook/cli/src/main.rs
  token/transfer-hook/cli/src/meta.rs
Labels: do-not-close

#6086 Fix typo in extensions.mdx
  docs/src/token-2022/extensions.mdx
Labels: community

#6120 [token-client] Added transfer-hook compatibility to `create_recipient_associated_account_and_transfer`
  token/client/src/token.rs
Labels: community

#6129 chore(docs): proofreading the docs
  docs/src/single-pool.mdx
  docs/src/theme/SearchBar/algolia.css
  docs/src/token-2022/extensions.mdx
  docs/src/token.mdx
Labels: community

#6058 stake-pool: make `update_validator_list_balance()` more ergonomic
  stake-pool/program/src/instruction.rs
  stake-pool/program/tests/decrease.rs
  stake-pool/program/tests/deposit.rs
  stake-pool/program/tests/deposit_edge_cases.rs
  stake-pool/program/tests/force_destake.rs
  stake-pool/program/tests/helpers/mod.rs
  stake-pool/program/tests/huge_pool.rs
  stake-pool/program/tests/increase.rs
  stake-pool/program/tests/redelegate.rs
  stake-pool/program/tests/set_epoch_fee.rs
  stake-pool/program/tests/set_withdrawal_fee.rs
  stake-pool/program/tests/update_stake_pool_balance.rs
  stake-pool/program/tests/update_validator_list_balance.rs
  stake-pool/program/tests/update_validator_list_balance_hijack.rs
  stake-pool/program/tests/vsa_remove.rs
  stake-pool/program/tests/withdraw_edge_cases.rs
Labels: community

#6135 [token-CLI] Add command_initialize_group to Token Cli
  token/cli/Cargo.toml
  token/cli/src/clap_app.rs
  token/cli/src/command.rs
  token/cli/tests/command.rs
Labels: community

#6154 Fix broken link in transfer-hook interface Readme.md
  token/transfer-hook/interface/README.md
Labels: automerge, community

#6161 Governance: bump spl-governance version to v4.0.0
  Cargo.lock
  governance/CHANGELOG.md
  governance/chat/program/Cargo.toml
  governance/program/Cargo.toml
Labels: community

#6162 Governance: bump spl-gov supporting crates to 0.1.4
  Cargo.lock
  governance/addin-api/Cargo.toml
  governance/addin-mock/program/Cargo.toml
  governance/chat/program/Cargo.toml
  governance/program/Cargo.toml
  governance/test-sdk/Cargo.toml
  governance/tools/Cargo.toml
Labels: community

#6150 token-cli: Add command_update_group_max_size to token CLI
  token/cli/src/clap_app.rs
  token/cli/src/command.rs
  token/cli/tests/command.rs
Labels: community

#6059 stake-pool-cli: don't send `UpdateValidatorListBalance` transactions for subslices of validator list that have already been updated
  stake-pool/cli/src/main.rs
  stake-pool/program/src/instruction.rs
Labels: community

#6173 fix: Use COptionPubkeyLayout for all COption fields
  token/js/src/instructions/initializeMint.ts
  token/js/src/instructions/initializeMint2.ts
  token/js/src/instructions/initializeMintCloseAuthority.ts
  token/js/src/instructions/setAuthority.ts
  token/js/test/e2e/initialize.test.ts
Labels: community

#6182 Update solana dependency version to allow 2.0.0
  account-compression/programs/noop/Cargo.toml
  associated-token-account/program-test/Cargo.toml
  associated-token-account/program/Cargo.toml
  binary-option/program/Cargo.toml
  binary-oracle-pair/program/Cargo.toml
  ci/solana-version.sh
  examples/rust/cross-program-invocation/Cargo.toml
  examples/rust/custom-heap/Cargo.toml
  examples/rust/logging/Cargo.toml
  examples/rust/sysvar/Cargo.toml
  examples/rust/transfer-lamports/Cargo.toml
  examples/rust/transfer-tokens/Cargo.toml
  feature-gate/program/Cargo.toml
  feature-proposal/cli/Cargo.toml
  feature-proposal/program/Cargo.toml
  governance/addin-api/Cargo.toml
  governance/addin-mock/program/Cargo.toml
  governance/chat/program/Cargo.toml
  governance/program/Cargo.toml
  governance/test-sdk/Cargo.toml
  governance/tools/Cargo.toml
  instruction-padding/program/Cargo.toml
  libraries/discriminator/Cargo.toml
  libraries/math/Cargo.toml
  libraries/pod/Cargo.toml
  libraries/program-error/Cargo.toml
  libraries/tlv-account-resolution/Cargo.toml
  libraries/type-length-value/Cargo.toml
  managed-token/program/Cargo.toml
  memo/program/Cargo.toml
  name-service/program/Cargo.toml
  record/program/Cargo.toml
  shared-memory/program/Cargo.toml
  single-pool/cli/Cargo.toml
  single-pool/program/Cargo.toml
  stake-pool/cli/Cargo.toml
  stake-pool/program/Cargo.toml
  stateless-asks/program/Cargo.toml
  token-collection/program/Cargo.toml
  token-group/example/Cargo.toml
  token-group/interface/Cargo.toml
  token-lending/cli/Cargo.toml
  token-lending/flash_loan_receiver/Cargo.toml
  token-lending/program/Cargo.toml
  token-metadata/example/Cargo.toml
  token-metadata/interface/Cargo.toml
  token-swap/program/Cargo.toml
  token-swap/program/fuzz/Cargo.toml
  token-upgrade/cli/Cargo.toml
  token-upgrade/program/Cargo.toml
  token-wrap/program/Cargo.toml
  token/cli/Cargo.toml
  token/client/Cargo.toml
  token/program-2022-test/Cargo.toml
  token/program-2022/Cargo.toml
  token/program/Cargo.toml
  token/transfer-hook/cli/Cargo.toml
  token/transfer-hook/example/Cargo.toml
  token/transfer-hook/interface/Cargo.toml
  utils/test-client/Cargo.toml
Labels: community

#6191 reduce cluttering by removing debug print command
  stake-pool/py/stake_pool/state.py
Labels: community

#6199 [token-2022] improve condition in Account::valid_account_data
  token/program-2022/src/state.rs
Labels: community

#6211 stake-pool-js: Fix not adding `increaseAdditionalValidatorStake` instruction to array
  stake-pool/js/src/index.ts
Labels: community
